# Pode validar antes do commit:

# terraform fmt;
# terraform validate;
# tflint;
# trailing whitespace;
# YAML;
# arquivos grandes;
# secrets acidentais.


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: validate-kustomize
        name: Validate Kustomize
        entry: kubectl kustomize apps/auth
        language: system
        pass_filenames: false