apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  namespace: analytics
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 111111111111.dkr.ecr.us-east-1.amazonaws.com/togglemaster-analytics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          # envFrom:
          #   - configMapRef:
          #       name: analytics-configmap
          #   - secretRef:
          #       name: analytics-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8005
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8005
          #   initialDelaySeconds: 20
          #   periodSeconds: 15