apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  #- ingress.yaml

  #Mantido como proposta de evolução arquitetural.
  #o Ingress compartilhado não é aplicado nesta demontração porque
  #os services estão distribuidos em namespaces diferentes, e o Ingress compartilhado não é capaz de rotear para serviços em namespaces diferentes.