apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-deployment
  namespace: evaluation-namespace
  labels:
    app: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: <>
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: evaluation-configmap
            - secretRef:
                name: evaluation-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

           
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 20
            periodSeconds: 15